addons:
  postgresql: '9.4'
dist: trusty
env:
  - DB=postgresql
language: ruby
rvm:
  - 2.6.2
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - postgresql