addons:
  postgresql: 10.3
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler -v 1.17.2
dist: trusty
language: ruby
rvm:
  - 2.6.2
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec